FROM apache/airflow:2.10.2-python3.12

USER root
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir duckdb==1.5.2 pandas==2.2.3 pyarrow==18.1.0
