services:
  duckdb-build:
    profiles: ["tools"]
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ecommerce-pipeline:latest
    working_dir: /app
    command: ["python", "src/pipeline_duckdb.py"]
    volumes:
      - ./:/app

  duckdb-ui:
    profiles: ["duckui"]
    build:
      context: .
      dockerfile: docker/Dockerfile.duckdb-ui
    image: ecommerce-duckdb-ui:latest
    container_name: ecommerce-duckdb-ui
    environment:
      DUCKDB_PATH: /app/ecommerce.duckdb
      DUCKDB_UI_INTERNAL_PORT: "4214"
      DUCKDB_UI_EXTERNAL_PORT: "4213"
      RUN_PIPELINE_CMD: "python /app/src/pipeline_duckdb.py"
    ports:
      - "4213:4213"
    volumes:
      - ./:/app

  airflow-init:
    build:
      context: .
      dockerfile: docker/Dockerfile.airflow
    image: ecommerce-airflow:latest
    container_name: ecommerce-airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/project/scripts
      - ./:/opt/airflow/project
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com || true"

  airflow-webserver:
    image: ecommerce-airflow:latest
    container_name: ecommerce-airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    ports:
      - "8080:8080"
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/project/scripts
      - ./:/opt/airflow/project
    command: webserver

  airflow-scheduler:
    image: ecommerce-airflow:latest
    container_name: ecommerce-airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/project/scripts
      - ./:/opt/airflow/project
    command: scheduler

volumes:
  airflow_data:
